---
ID: "cab60624-6455-4735-8543-4653bac6af37"
Parent: "047c73d0-38d7-41a0-a0f2-1b865ccf4fb0"
Template: "047c73d0-38d7-41a0-a0f2-1b865ccf4fb0"
Path: /sitecore/templates/Project/BeeGhentle/Partial Design/__Standard Values
DB: master
SharedFields:
- ID: "55faae90-3bba-4f7f-96fe-13c3f40055ff"
  Hint: Signature
  Value: "__standard-values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T051648Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
