---
ID: "829f6c44-6075-49b0-bb2a-daf5d8b4875d"
Parent: "2fe84d01-19ad-4cf7-8dd2-553788249d4f"
Template: "2fe84d01-19ad-4cf7-8dd2-553788249d4f"
Path: /sitecore/templates/Project/BeeGhentle/Event/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T084220Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
