---
ID: "8239723d-ed52-424d-b243-1847f76ac346"
Parent: "6b82c817-79fb-4374-bd3f-500194f78bb4"
Template: "6b82c817-79fb-4374-bd3f-500194f78bb4"
Path: /sitecore/templates/Project/BeeGhentle/Tenant/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T051648Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
