---
ID: "5159095a-8689-4b58-a85d-cf5efb6020e5"
Parent: "c3a7b309-1f83-4332-8860-fe2389ed3b6b"
Template: "c3a7b309-1f83-4332-8860-fe2389ed3b6b"
Path: /sitecore/templates/Project/BeeGhentle/Page Design/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T051648Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
