---
ID: "48d7f6c3-5f06-43d9-9499-31db91980118"
Parent: "457db449-cc2e-40c6-8655-f93c1b4b7c5c"
Template: "26fce9bf-0256-458d-8281-a713a5bf5520"
Path: /sitecore/content/BeeGhentle/SUG/Presentation/Cache Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T051901Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
