---
ID: "c9ca51a7-b911-4db2-ac2c-8b0604ba6618"
Parent: "99ac6f0f-2483-46d1-92bb-91c2d81a21bf"
Template: "99ac6f0f-2483-46d1-92bb-91c2d81a21bf"
Path: /sitecore/templates/Project/BeeGhentle/Settings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T051648Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
